---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-"ubuntu:20.04"}

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      remote_tmp: /var/tmp/molecule

verifier:
  name: ansible
