---
- name: Install apt pre-requisites
  become: true
  apt:
    name: "{{ pre_reqs }}"
    state: present
    update_cache: yes
  become: yes

- name: Install pip pre-requisites
  pip:
    name:
      - setuptools
      - wheel
      - virtualenv
    state: present
    executable: pip3

- name: Create molecule virtualenv dir
  file:
    path: ~/.virtualenvs/molecule
    state: directory
    mode: "0755"

- name: Copy requirements
  copy:
    src: requirements.txt
    dest: /var/tmp/requirements.txt
    mode: '0644'

- name: Install requirements in virtualenv
  pip:
    requirements: /var/tmp/requirements.txt
    virtualenv_python: python3
    virtualenv: ~/.virtualenvs/molecule
