---
- name: Install Pre-requisite Packages
  become: true
  apt:
    name: "{{ prereq_pkgs }}"
    state: present
    update_cache: yes

- name: Add helm apt key
  become: true
  apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    state: present

- name: Add helm repo
  become: true
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main

- name: Install helm
  become: true
  apt:
    name: helm
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Create bash_completion.d dir
  file:
    name: /etc/bash_completion.d
    state: directory
    mode: '0755'

- name: Helm Completion
  shell: helm completion bash > /etc/bash_completion.d/helm
  changed_when: false
