---
- name: Verify
  hosts: all
  tasks:
  - name: Check that the gitcconfig exists
    stat:
      path: "/home/{{ ansible_user }}/.gitconfig"
    register: stat_result

  - name: Assert file exists
    assert:
      that:
        - stat_result.stat.exists

  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Verify Packages
    assert:
      that: "'{{ item }}' in ansible_facts.packages"
    with_items:
      - git
  vars:
    ansible_user: root
