---
- name: Verify
  hosts: all
  tasks:
  - name: Check that the somefile.conf exists
    stat:
      path: "/home/{{ ansible_user }}/.gitconfig"
    register: stat_result

  - name: Assert file exists
    assert:
      that:
        - stat_result.stat.exists

  vars:
    ansible_user: root
