---
- name: Converge
  hosts: all
  tasks:
    - name: "Include git"
      include_role:
        name: "git"
    - name: "Include kubectl"
      include_role:
        name: "kubectl"
  vars:
    ansible_user: root
