---
- name: Install pre-requisites
  apt:
    name: 
      - gnupg
    state: present
    update_cache: yes

- include: ubuntu18.yaml
  when: release_name == 'bionic'

- include: ubuntu20.yaml
  when: release_name == 'focal'
