---
- name: Install pre-requisites
  apt:
    name: "{{ prereq_pkgs }}"
    state: present

- name: Install VS Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
    state: present
    update_cache: yes
    cache_valid_time: 3600
