---
- name: Install pre-requisites
  apt:
    name: "{{ prereq_pkgs }}"
    state: present

- name: Install VS Code
  snap:
    name: code
    classic: yes

- name: Create config dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  loop:
    - "/home/{{ ansible_user }}/.config"
    - "/home/{{ ansible_user }}/.config/Code"
    - "/home/{{ ansible_user }}/.config/Code/User"


- name: Add settings template
  template:
    src: settings.json.j2
    dest: "/home/{{ ansible_user }}/.config/Code/User/settings.json"
    force: yes
