---
- name: Pull kubectx
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "{{ kubectx_dir }}"
    clone: yes
    version: master
    update: no

- name: Create symlinks for PATH and bash completion
  file:
    src: "{{ kubectx_dir }}/kubectx"
    dest: /usr/local/bin/kubectx
    state: link

- name: Create symlinks for PATH and bash completion
  file:
    src: "{{ kubectx_dir }}/kubens"
    dest: /usr/local/bin/kubens
    state: link

- name: Create symlinks for PATH and bash completion
  become: true
  file:
    src: "{{ kubectx_dir }}/completion/kubens.bash"
    dest: /etc/bash_completion.d/kubens
    state: link

- name: Create symlinks for PATH and bash completion
  become: true
  file:
    src: "{{ kubectx_dir }}/completion/kubectx.bash"
    dest: /etc/bash_completion.d/kubectx
    state: link
