---
- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    timeout: 30

- name: Make Executable
  file:
    path: /usr/local/bin/docker-compose
    mode: +x
