---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Copy git config
  template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    mode: 0640