---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Add dir for {{ ansible_user }}
  file:
    path: "/home/{{ ansible_user }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: Copy git config
  template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    mode: 0640
