---
- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes

- name: Create user dir
  ansible.builtin.file:
    path: /home/{{ ansible_user }}
    state: directory

- name: Copy git config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    mode: 0640
