---
- name: Install Pre-requisite Packages
  apt:
    name: "{{ prereq_pkgs }}"
    state: present
    update_cache: yes

- name: Add an Apt signing key for Az CLI
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/microsoft.asc.gpg

- name: Add azure cli repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main"
    filename: azure-cli

- name: Install azure cli
  apt:
    name: azure-cli
    update_cache: yes
