---
- name: Install pre-requisite packages
  apt:
    name:
      - apt-transport-https
      - curl

- name: Add Brave apt key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg

- name: Add Brave repo
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release

- name: Install Brave
  apt:
    name: brave-browser
    state: present
    update_cache: yes
