---
- name: Install pre-requisite pkgs
  apt:
    name:
      - apt-transport-https
      - curl

- name: Add Tor repo
  apt_repository:
    repo: "deb https://deb.torproject.org/torproject.org/ {{ ansible_distribution_release }} main"
    filename: tor
    update_cache: no

- name: Add Tor keys
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/torproject.gpg

- name: Install Tor packages
  apt:
    name:
      - tor
      - tor-geoipdb
      - torsocks
      - deb.torproject.org-keyring
    state: present
    update_cache: yes
