---
- name: "Converge"
  hosts: all
  become: true
  roles:
    - role: include
      tags: debug

    - role: debug
      tags: debug

    - role: git
      git_user: CHANGEME
      git_email: CHANGEME
      tags:
        - common

    - role: docker
      tags:
        - devops

    - role: azure_cli
      tags:
        - devops

    - role: google_cloud
      tags:
        - devops

    - role: docker_compose
      tags:
        - devops

    - role: bash_it
      become: no
      tags:
        - common

    - role: virtual_box
      tags:
        - devops
        - vbox

    - role: vagrant
      tags:
        - devops

    - role: terraform
      tags:
        - devops

    - role: kubectl
      tags:
        - devops

    - role: helm
      tags:
        - devops

    - role: vs_code
      user_data_dir: "--user-data-dir /root"
      tags:
        - devops

    - role: browsers
      tags:
        - common

    - role: misc

    - role: multiboot

    - role: virtualenv

  vars:
    ansible_user: root
    running_on_molecule: yes
    ansible_python_interpreter: /usr/bin/python3
    bash_it_user: "/root"
    molecule_remote_src: yes
