---
- name: "Converge"
  hosts: all
  become: true
  roles:
    - role: include
      tags: debug

    - role: debug
      tags: debug

    - role: git
      git_user: CHANGEME
      git_email: CHANGEME
      tags:
        - common

    - role: docker
      tags:
        - devops

    - role: azure-cli
      # Az CLI has no install method for ubuntu 20
      release_name: bionic
      tags:
        - devops

    - role: google-cloud
      tags:
        - devops

    - role: docker-compose
      tags:
        - devops

    - role: bash-it
      become: no
      tags:
        - common

    - role: virtual-box
      tags:
        - devops
        - vbox

    - role: vagrant
      tags:
        - devops

    - role: terraform
      tags:
        - devops

    - role: kubectl
      tags:
        - devops

    - role: helm
      tags:
        - devops

    - role: vs-code
      tags:
        - devops

    - role: browsers
      tags:
        - common

    - role: misc

  vars:
    ansible_user: root
    running_on_molecule: yes
    ansible_python_interpreter: /usr/bin/python3
    bash_it_user: "/root"
    molecule_remote_src: yes


## TODO List ##

## Tools ##
## chrome extenstions
# multisystem usb boot
## virtualenvs // molecule
