---
- name: Install gcloud pre-requisites
  apt:
    name: "{{ prereq_pkgs }}"
    state: present

- name: Add gcloud apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: Add gcloud repo
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk

- name: install google-cloud-sdk
  apt:
    name: google-cloud-sdk
    state: present
    update_cache: yes
    cache_valid_time: 3600
