---
- name: Converge
  hosts: all
  tasks:
    - name: "Include docker"
      include_role:
        name: "docker"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    running_on_molecule: yes
