---
- name: Converge
  hosts: all
  tasks:

    - name: "Include include"
      include_role:
        name: "include"

    - name: "Include docker"
      include_role:
        name: "docker"
  vars:
    ansible_python_interpreter: /usr/bin/python3
