---
- name: Verify
  hosts: all
  tasks:
  - name: Example assertion
    assert:
      that: true

  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Verify Packages
    assert:
      that: "'{{ item }}' in ansible_facts.packages"
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
