---
- include: ubuntu18.yaml
  when: release_name == 'bionic'

- include: ubuntu20.yaml
  when: release_name == 'focal' and not running_on_molecule | bool

- debug:
    msg: "Ansible using python interpreter {{ ansible_python_interpreter }}"
