---
- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Add User to Docker Group
  become: true
  user:
    append: yes
    groups: docker
    name: "{{ ansible_user_id }}"

- name: Debug system restart
  debug:
    msg: Restart system for group changes to take affect
