---
- hosts: all
  become: true
  roles:
    - role: prereqs
      tags: 
        - common

    - role: docker
      tags:
        - devops

    - role: vs-code
      tags:
        - devops 

    - role: azure-cli
      tags:
        - devops

    - role: google-cloud
      tags:
        - devops

    - role: docker-compose
      tags:
        - devops

    - role: bash-it
      become: no
      tags:
        - common

    - role: virtual-box
      tags:
        - devops

    - role: vagrant
      tags:
        - devops

    - role: terraform
      tags:
        - devops
        - debug

## TODO List ##

## Tools ##

# multisystem usb boot
# kubectl
# helm
# git config

# Browsers 
# tor
# brave 
# chrome

#Misc
# calibre
# spotify