---
- hosts: all
  become: true
  roles:
    - role: git
      tags: 
        - common

    - role: docker
      tags:
        - devops

    - role: vs-code
      tags:
        - devops 

    - role: azure-cli
      tags:
        - devops

    - role: google-cloud
      tags:
        - devops

    - role: docker-compose
      tags:
        - devops

    - role: bash-it
      become: no
      tags:
        - common

    - role: virtual-box
      tags:
        - devops

    - role: vagrant
      tags:
        - devops

    - role: terraform
      tags:
        - devops

    - role: kubectl
      tags:
        - devops
    
    - role: helm
      tags:
        - devops
    
    - role: browsers
      tags:
        - common

    - role: misc
      tags:
        - debug

## TODO List ##

## Tools ##
## VS code extensions // config
## chrome extenstions
# multisystem usb boot