---
- hosts: all
  become: true
  roles:
    - role: include
      tags: debug

    - role: debug
      tags: debug

    - role: git
      tags:
        - common

    - role: docker
      tags:
        - devops

    - role: azure_cli
      tags:
        - devops

    - role: google_cloud
      tags:
        - devops

    - role: docker_compose
      tags:
        - devops

    - role: bash_it
      become: no
      tags:
        - common

    - role: virtual_box
      tags:
        - devops
        - vbox

    - role: vagrant
      tags:
        - devops

    - role: terraform
      tags:
        - devops

    - role: kubectl
      tags:
        - devops

    - role: helm
      tags:
        - devops

    - role: vs_code
      tags:
        - devops

    - role: browsers
      tags:
        - common

    - role: misc

    - role: multiboot

    - role: virtualenv
      become: no
