---
- hosts: all
  roles:

    - role: debug
      tags: debug

    # - role: git
    #   tags:
    #     - common
    #     - changed

    # - role: docker
    #   tags:
    #     - devops

    - role: azure_cli
      tags:
        - devops

    - role: google_cloud
      tags:
        - devops

    # - role: virtual_box
    #   tags:
    #     - devops
    #     - vbox
    #     - changed

    - role: vagrant
      tags:
        - devops
        - changed

    - role: terraform
      tags:
        - devops
        - changed

    - role: kubectl
      tags:
        - devops
        - changed

    - role: helm
      tags:
        - devops
        - changed

    # - role: vs_code
    #   tags:
    #     - devops

    # - role: browsers
    #   tags:
    #     - common

    - role: misc

    - role: multiboot

    - role: virtualenv
      become: no

    - role: ohmyzsh
