---
name: branch-build
on:
  push:
    branches:
      - !master
  workflow_dispatch:


jobs:
  host-test-changed:
    name: Host ansible run - changed tags
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo.
        uses: actions/checkout@v2

      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run ansible playbook
        run: |
              set -e
              make install-changed
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
