---
name: CI
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 20 * * 5'
  workflow_dispatch:

jobs:
  molecule-test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu:20.04
          - linuxmintd/mint20-amd64
          - linuxmintd/mint20.2-amd64
    steps:
      - name: Check out git repo.
        uses: actions/checkout@v2

      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: make requirements

      - name: Test include role
        run: cd roles/include && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test debug role
        run: cd roles/debug && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test git role
        run: cd roles/git && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test docker role
        run: cd roles/docker && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test azure_cli role
        run: cd roles/azure_cli && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test google_cloud role
        run: cd roles/google_cloud && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test docker_compose role
        run: cd roles/docker_compose && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test virtual_box role
        run: cd roles/virtual_box && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test vagrant role
        run: cd roles/vagrant && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test terraform role
        run: cd roles/terraform && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test kubectl role
        run: cd roles/kubectl && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test helm role
        run: cd roles/helm && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test vs_code role
        run: cd roles/vs_code && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test browsers role
        run: cd roles/browsers && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test misc role
        run: cd roles/misc && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test multiboot role
        run: cd roles/multiboot && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test virtualenv role
        run: cd roles/virtualenv && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      # - name: Run molecule test
      #   run: cd roles/molecule && molecule test
      #   env:
      #     PY_COLORS: '1'
      #     ANSIBLE_FORCE_COLOR: '1'
      #     MOLECULE_DISTRO: ${{ matrix.distro }}

  host-test:
    name: Host ansible run
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo.
        uses: actions/checkout@v2

      - name: Set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run ansible playbook
        run: |
              set -e
              echo $VAULT > ./.vault
              make install
        env:
          VAULT: ${{ secrets.VAULT_PW }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'